app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', 'HomeController@index');

// Admin
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth.checkrole:admin']], function() {

    // Categories
    Route::group(['prefix' => 'categories', 'as' => 'categories.'], function() {
        Route::get('', ['uses' => 'CategoriesController@index', 'as' => 'index']);
        Route::get('create', ['uses' => 'CategoriesController@create', 'as' => 'create']);
        Route::get('edit/{id}', ['uses' => 'CategoriesController@edit', 'as' => 'edit']);
        Route::post('store', ['uses' => 'CategoriesController@store', 'as' => 'store']);
        Route::post('update/{id}', ['uses' => 'CategoriesController@update', 'as' => 'update']);
    });

    // Clients
    Route::group(['prefix' => 'clients', 'as' => 'clients.'], function() {
        Route::get('', ['uses' => 'ClientsController@index', 'as' => 'index']);
        Route::get('create', ['uses' => 'ClientsController@create', 'as' => 'create']);
        Route::get('edit/{id}', ['uses' => 'ClientsController@edit', 'as' => 'edit']);
        Route::post('store', ['uses' => 'ClientsController@store', 'as' => 'store']);
        Route::post('update/{id}', ['uses' => 'ClientsController@update', 'as' => 'update']);
    });

    // Products
    Route::group(['prefix' => 'products', 'as' => 'products.'], function() {
        Route::get('', ['uses' => 'ProductsController@index', 'as' => 'index']);
        Route::get('create', ['uses' => 'ProductsController@create', 'as' => 'create']);
        Route::get('edit/{id}', ['uses' => 'ProductsController@edit', 'as' => 'edit']);
        Route::post('store', ['uses' => 'ProductsController@store', 'as' => 'store']);
        Route::post('update/{id}', ['uses' => 'ProductsController@update', 'as' => 'update']);
        Route::get('destroy/{id}', ['uses' => 'ProductsController@destroy', 'as' => 'destroy']);
    });

    // Orders
    Route::group(['prefix' => 'orders', 'as' => 'orders.'], function() {
        Route::get('', ['uses' => 'OrdersController@index', 'as' => 'index']);
        Route::get('{id}', ['uses' => 'OrdersController@edit', 'as' => 'edit']);
        Route::post('update/{id}', ['uses' => 'OrdersController@update', 'as' => 'update']);
    });

    // Cupoms
    Route::group(['prefix' => 'cupoms', 'as' => 'cupoms.'], function() {
        Route::get('', ['uses' => 'CupomsController@index', 'as' => 'index']);
        Route::get('create', ['uses' => 'CupomsController@create', 'as' => 'create']);
        Route::post('store', ['uses' => 'CupomsController@store', 'as' => 'store']);
        Route::get('edit/{id}', ['uses' => 'CupomsController@edit', 'as' => 'edit']);
        Route::post('update/{id}', ['uses' => 'CupomsController@update', 'as' => 'update']);
    });
});

// Customer
Route::group(['prefix' => 'customer', 'as' => 'customer.', 'middleware' => ['auth.checkrole:client']], function() {

    // Checkout
    Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
        Route::get('', ['uses' => 'CheckoutController@index', 'as' => 'index']);
        Route::get('create', ['uses' => 'CheckoutController@create', 'as' => 'create']);
        Route::post('store', ['uses' => 'CheckoutController@store', 'as' => 'store']);
    });

});

// OAuth2
Route::post('oauth/access_token', function() {
    return Response::json(Authorizer::issueAccessToken());
});

// API
Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => ['oauth'], 'namespace' => 'Api'], function() {

    Route::get('authenticated', ['as' => 'authenticated', 'uses' => 'AuthenticatedController@index']);

    // Client
    Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => ['oauth.checkrole:client'], 'namespace' => 'Client'], function() {
        Route::resource('order', 'ClientCheckoutController', ['except' => ['create', 'edit', 'destroy']]);
    });

    // Deliveryman
    Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => ['oauth.checkrole:deliveryman'], 'namespace' => 'Deliveryman'], function() {
        Route::resource('order', 'DeliverymanCheckoutController', ['except' => ['create', 'edit', 'destroy', 'store']]);
        Route::patch('order/{id}/update-status', ['as' => 'order.update_status', 'uses' => 'DeliverymanCheckoutController@updateStatus']);
    });

});

app/Models/Order.php
<?php

namespace CodeDelivery\Models;

use Illuminate\Database\Eloquent\Model;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

class Order extends Model implements Transformable
{
    use TransformableTrait;

    protected $fillable = [
        'client_id',
        'user_deliveryman_id',
        'total',
        'status'
    ];

    public function cupom()
    {
        return $this->belongsTo(Cupom::class);
    }

    public function client()
    {
        return $this->belongsTo(Client::class);
    }

    public function items()
    {
        return $this->hasMany(OrderItem::class);
    }

    public function deliveryman()
    {
        return $this->belongsTo(User::class, 'user_deliveryman_id', 'id');
    }

}

app/Http/Controllers/OrdersController.php
<?php

namespace CodeDelivery\Http\Controllers;

use CodeDelivery\Repositories\OrderRepository;
use CodeDelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

use CodeDelivery\Http\Requests;

class OrdersController extends Controller
{
    /**
     * @var OrderRepository
     */
    private $repository;

    public function __construct(OrderRepository $repository)
    {
        $this->repository = $repository;
    }

    public function index()
    {
        $orders = $this->repository->paginate();
        return view('admin.orders.index', compact('orders'));
    }

    public function edit($id, UserRepository $userRepository)
    {
        $order = $this->repository->find($id);
        $list_status = [0 => 'Pendente', 1 => 'A Caminho', 2 => 'Entregue'];
        $deliveryman = $userRepository->getDeliveryman();

        return view('admin.orders.edit', compact('order', 'list_status', 'deliveryman'));
    }

    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->repository->update($all, $id);

        return redirect()->route('admin.orders.index');
    }
}

resources/views/customer/order/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Novo Pedido</h1>
                @include('errors._check')
            </div>
        </div>

        {!! Form::open(['route' => 'customer.order.store']) !!}

        <div class="row">
            <div class="col-md-12">

                <div class="form-group">
                    {!! Form::label('total', 'Total') !!}
                    <p id="total"></p>
                    <a href="#" id="btnNewItem" class="btn btn-primary">Novo Item</a>
                </div>

                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th>Produto</th>
                        <th width="1">Quantidade</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>
                            <select name="items[0][product_id]" class="form-control">
                                @forelse($products as $p)
                                    <option value="{{ $p->id }}" data-price="{{ $p->price }}">{{ $p->name }} --- {{ $p->price }}</option>
                                @empty
                                @endforelse
                            </select>
                        </td>
                        <td>
                            {!! Form::text('items[0][qtd]', 1, ['class' => 'form-control']) !!}
                        </td>
                    </tr>
                    </tbody>
                </table>

                <div class="form-group">
                    {!! Form::submit('Criar Pedido', ['class' => 'btn btn-primary']) !!}
                </div>

            </div>
        </div>

        {!! Form::close() !!}

    </div>

@endsection

@section('post-script')
    <script>
        $(function() {
            $('#btnNewItem').on('click', function() {
                var row = $('table tbody > tr:last'),
                    newRow = row.clone(),
                    length = $('table tbody tr').length;

                newRow.find('td').each(function() {
                    var td = $(this),
                        input = td.find('input,select'),
                        name = input.attr('name');

                    input.attr('name', name.replace((length - 1) + "", length + ""));
                });

                newRow.find('input').val(1);
                newRow.insertAfter(row);

                calculateTotal();

                return false;
            });

            $('body').on('change', 'select', function() {
                calculateTotal();
            });

            $('body').on('blur', 'input[name*=qtd]', function() {
                calculateTotal();
            });

        });

        calculateTotal();

        function calculateTotal() {
            var total = 0,
                trLen = $('table tbody tr').length,
                tr = null, price, qtd;

            for(var i = 0; i < trLen; i++) {
                tr = $('table tbody tr').eq(i);
                price = tr.find(':selected').data('price');
                qtd = tr.find('input').val();
                total += price * qtd;
            }

            $('#total').html(total);
        }
    </script>
@endsection

resources/views/customer/order/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Pedidos</h1>
                <a href="{{ route('customer.order.create') }}" class="btn btn-primary">Novo Pedido</a>
                <br><br>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table table-hover table-striped">
                    <thead>
                    <tr>
                        <th width="1">ID</th>
                        <th>Total</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                    @forelse($orders as $order)
                        <tr>
                            <td>{{ $order->id }}</td>
                            <td>{{ $order->total }}</td>
                            <td>{{ $order->status }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3">Nenhum registro no momento</td>
                        </tr>
                    @endforelse
                    </tbody>
                </table>

                {!! $orders->render() !!}
            </div>
        </div>

    </div>

@endsection